-
  name: play on group test
  hosts: test 
  vars:
    gns: 9.8.8.8
  tasks:
    - name: add google dns
      lineinfile:
        path: /etc/resolv.conf
        regexp: 'nameserver {{gns}}'
        state: absent
